import { useEffect, useState } from 'react';
import { RotateCcw, ArchiveRestore } from 'lucide-react';
import { api } from '../../services/apiService';
import { useAuth } from '../../context/AuthContext';
export default function ArchivedInterns() {
 const { profile } = useAuth(); const [interns,setInterns]=useState<any[]>([]); const [error,setError]=useState(''); const load=()=>api.getArchivedInterns().then(setInterns).catch(()=>setError('Could not load archived interns.'));
 useEffect(()=>{load()},[]); const reactivate=async(i:any)=>{if(!profile||!confirm(`Reactivate ${i.name}?`))return; try{await api.reactivateIntern(i.uid,profile.uid);load()}catch(e:any){setError(e.message)}};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Archived Interns</h1><p className="text-sm text-slate-500">Archived accounts retain their attendance, work logs, requests, and reports.</p></div>{error&&<p className="text-red-600 text-sm">{error}</p>}<div className="bg-white rounded-2xl border border-slate-100 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-400 uppercase text-[11px]"><tr><th className="p-4">Intern</th><th className="p-4">Reason</th><th className="p-4">Archived</th><th className="p-4">By</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{interns.map(i=><tr key={i.uid} className="border-t"><td className="p-4 font-bold">{i.name}<div className="text-slate-400 font-normal">{i.department||'No department'}</div></td><td className="p-4">{i.archive_reason}</td><td className="p-4">{i.archived_at ? new Date(i.archived_at).toLocaleDateString() : '—'}</td><td className="p-4">{i.archived_by_name||'—'}</td><td className="p-4"><span className="text-amber-700 bg-amber-50 px-2 py-1 rounded-full">Archived</span></td><td className="p-4"><button onClick={()=>reactivate(i)} className="flex gap-1 text-primary font-bold"><RotateCcw size={15}/> Reactivate</button></td></tr>)}{!interns.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-400"><ArchiveRestore className="mx-auto mb-2"/>No archived interns.</td></tr>}</tbody></table></div></div>
}
